### ISSUE TITLE
Accounting for ^ in package versions

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/aspect-sdm#9]
![Screenshot 2019-09-02 06 09 56](https://user-images.githubusercontent.com/1643888/64116901-80937e80-cd48-11e9-8cd6-5102c91bfaab.png)

**Comment by cdupuis** [comment]
Those are two fundamentally different version and the current policy of `3.5.3` is correct whereas applying `^3.5.3` does break apollo.

**Comment by slimslenderslacks** [comment]
the issue was about making improving the message to help users understand things like:

**Comment by cdupuis** [comment]
@slimslenderslacks sorry, that’s still not clear to me. Could you provide more detail on what you’d like to see changed?

**Comment by slimslenderslacks** [comment]
3.5.3 and ^3.5.3 look kind of like the same thing - but since ^3.5.3 can end up with something very different in package-lock.json (depending on what's in npmjs), we can indicate that for ^ and ~.  I don't know users will want ^ and ~ in their policies but if they use them, you could make the argument that a policy of ^3.5.3 is also not equal to a policy of ^3.4.0 or 3.6.2 even though they overlap.  So when going from something like 3.5.3 -> [~|^]3.5.3, it makes sense to say something too.
